// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzupsyhyoztaekcwmels.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6dXBzeWh5b3p0YWVrY3dtZWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjMwNjEsImV4cCI6MjA3NDAzOTA2MX0.SAclOv-CQj2Rp2sXmSSZh_D_RNfjti3W9GRx0QXPjsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});